name: 打包上传部署到阿里云

on:
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取源代码
        - name: 迁出代码
      # 使用action库来获取源码
          uses: actions/checkout@main

         # 安装node
        - name: 安装nodejs
          uses: actions/setup-node@v1
          with:
              node-version: 18.0.0
        - name: 安装依赖
          run: npm install
        - name: 打包
          run: npm run build
        - name: 上传服务器
          uses: appleboy/scp-action@v0.1.6
          with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              rm: true
              overwrite: true
              source: "dist"
              target: "/www/wwwroot"
          
          
                

              
      
